#pragma once
#define SCREEN_WIDTH 1600
#define SCREEN_HEIGHT 900
#define SPLASH_STATE_SHOWTIME 3.0f
#define SPLASH_SCREEN_BACKGROUND_FILEPATH "Resources/Images/SplashState.jpg"
#define MAIN_MENU_BACKGROUND_FILEPATH  "Resources/Images/MainMenu.jpg"
#define FONT_MENU_FILEPATH "Resources/Fonts/Comic.ttf"
#define COIN_SOUND_FILEPATH "Resources/Sound/coin.wav"
#define PLAYING_BACKGROUND_FILEPATH "Resources/Images/Playing_BackGround.png"
#define BLOCK_FILE_PATH "Resources/Images/Block.png" 
#define POWER_BLOCK_FILE_PATH "Resources/Images/block_power.jpg"
#define BLOCK_PIECE_FILE_PATH "Resources/Images/block_piece.png" 
#define GOOMBA_FILEPATH "Resources/Images/Goomba.png"
#define DEAD_GOOMBA_FILEPATH "Resources/Images/DeadGoomba.png"
#define GROUND_FILEPATH "Resources/Images/Land.png"
#define MARIO_FRAME_01 "Resources/Images/mario.png"
#define MARIO_FRAME_02 "Resources/Images/mario2.png"
#define MARIO_FRAME_03 "Resources/Images/mario3.png"
#define MARIO_DEATH "Resources/Images/mariodeath.png"
#define MARIO_PIPE_FILEPATH "Resources/images/PipeUp.png"
#define MARIO_JUMP_SOUND_FILEPATH "Resources/Sound/jump.wav"
#define BRICK_SMASH_JUMP_SOUND_FILEPATH "Resources/Sound/bricksmash.wav"
#define COIN_FRAME_1 "Resources/Images/coins1.png"
#define COIN_FRAME_2 "Resources/Images/coins2.png"
#define COIN_FRAME_3 "Resources/Images/coins3.png"
#define COIN_FRAME_4 "Resources/Images/coins4.png"
#define COIN_FRAME_5 "Resources/Images/coins5.png"
#define COIN_FRAME_6 "Resources/Images/coins6.png"
#define SCALEX 0.5
#define SCALEY 0.5
#define MARIO_ANIMATION_DURATION  0.2f
#define COIN_ANIMATION_DURATION 0.3f
#define NUM_COINS 50
#define MARIO_SPEED 7.f
#define	FALLING_STATE 1
#define STILL_STATE 2
#define DEAD_STATE 5
#define FLYING_STATE 3
#define MINI_FLYING_STATE 4 
#define JUMP_DURATION 0.6f
#define JUMP_DISTANCE -1150.f
#define GRAVITY  40.f
#define MEGA_GRAVITY 5.f
#define NUM_GROUNDS 15
#define NUM_BLOCKS 50
#define MUSIC_PATH "Resources/Sound/theme.wav"
#define BLOCK_ANIMATION_DURATION  0.1f
#define NUM_GOOMBAAS 10


